program = fndef*;

fndef = "int" ident "(" params? ")" "{" stmt* "}";

params = "int" ident
       | "int" ident "," params;

stmt = expr ";"
     | "if" "(" expr ")" stmt ("else" stmt)?
     | "return" expr ";"
     | "{" (stmt | declaration)* "}"
     ;

declaration = "int" declarator ";";

declarators = ident
            | "*" declarator;

expr = assign;

assign = equality ("=" assign)?;

equality = relational ("==" relational | "!=" relational)*;

relational = add ("<=" add | ">=" add | "<" add | ">" add)*;

add = mul ("+" mul | "-" mul)*;

mul = unary ("*" unary | "/" unary)*;

unary = ("+" | "-")? primary;

primary = num
        | ident ( "("  ")" )?
        | "&" unary
        | "*" unary
        | "(" expr ")";
